# Generated by Django 5.2.7 on 2025-11-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantenimiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordendetrabajo',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En Proceso', 'En Proceso'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=15),
        ),
    ]
